//Login actions type
export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

//profile action types
export const FETCH_PROFILE_BEGIN = "FETCH_PROFILE_BEGIN";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAILURE = "FETCH_PROFILE_FAILURE";

//Register actions types
export const REGISTER_BEGIN = "REGISTER_BEGIN";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

//Fetch RDV actions types
export const FETCH_RDV_BEGIN = "FETCH_RDV_BEGIN";
export const FETCH_RDV_SUCCESS = "FETCH_RDV_SUCCESS";
export const FETCH_RDV_FAILURE = "FETCH_RDV_FAILURE";

//Fetch RDV actions types
export const FETCH_CONSULTATION_BEGIN = "FETCH_CONSULTATION_BEGIN";
export const FETCH_CONSULTATION_SUCCESS = "FETCH_CONSULTATION_SUCCESS";
export const FETCH_CONSULTATION_FAILURE = "FETCH_CONSULTATION_FAILURE";
export const FETCH_NEXT_CONSULTATION_SUCCESS =
	"FETCH_NEXT_CONSULTATION_SUCCESS";

//add new RDV actions types
export const ADD_RDV_BEGIN = "ADD_RDV_BEGIN";
export const ADD_RDV_SUCCESS = "ADD_RDV_SUCCESS";
export const ADD_RDV_FAILURE = "ADD_RDV_FAILURE";

//update RDV status actions types
export const UPDATE_RDV_BEGIN = "UPDATE_RDV_BEGIN";
export const UPDATE_RDV_SUCCESS = "UPDATE_RDV_SUCCESS";
export const UPDATE_RDV_FAILURE = "UPDATE_RDV_FAILURE";

//Fetch Medecins actions types
export const FETCH_MEDECIN_BEGIN = "FETCH_MEDECIN_BEGIN";
export const FETCH_MEDECIN_SUCCESS = "FETCH_MEDECIN_SUCCESS";
export const FETCH_MEDECIN_FAILURE = "FETCH_MEDECIN_FAILURE";

//Get Medecin detail actions types
export const GET_DETAIL_MEDECIN_BEGIN = "GET_DETAIL_MEDECIN_BEGIN";
export const GET_DETAIL_MEDECIN_FAILURE = "GET_DETAIL_MEDECIN_FAILURE";
export const GET_DETAIL_MEDECIN_SUCCESS = "GET_DETAIL_MEDECIN_SUCCESS";

//Get patient detail
export const GET_PATIENT_DETAIL_BEGIN = "GET_PATIENT_DETAIL_BEGIN";
export const GET_PATIENT_DETAIL_SUCCESS = "GET_PATIENT_DETAIL_SUCCESS";
export const GET_PATIENT_DETAIL_FAILURE = "GET_PATIENT_DETAIL_FAILURE";

//add new consulation actions types
export const ADD_CONSULTATION_BEGIN = "ADD_CONSULTATION_BEGIN";
export const ADD_CONSULTATION_SUCCESS = "ADD_CONSULTATION_SUCCESS";
export const ADD_CONSULTATION_FAILURE = "ADD_CONSULTATION_FAILURE";

//get specialite and medecins par specialite
export const FETCH_SPECIALITE_BEGIN = "FETCH_SPECIALITE_BEGIN";
export const FETCH_SPECIALITE_SUCCESS = "FETCH_SPECIALITE_SUCCESS";
export const FETCH_SPECIALITE_SERVICE_SUCCESS =
	"FETCH_SPECIALITE_SERVICE_SUCCESS";
export const FETCH_SPECIALITE_FAILURE = "FETCH_SPECIALITE_FAILURE";

//send new expertise request
export const DEMANDE_AVIS_BEGIN = "DEMANDE_AVIS_BEGIN";
export const DEMANDE_AVIS_SUCCESS = "DEMANDE_AVIS_SUCCESS";
export const DEMANDE_AVIS_FAILURE = "DEMANDE_AVIS_FAILURE";

//get expertise requests sent

export const FETCH_AVIS_BEGIN = "FETCH_AVIS_BEGIN";
export const FETCH_AVIS_SUCCESS = "FETCH_AVIS_SUCCESS";
export const FETCH_AVIS_FAILURE = "FETCH_AVIS_FAILURE";

//get expertise requests sent
export const UPDATE_AVIS_BEGIN = "UPDATE_AVIS_BEGIN";
export const UPDATE_AVIS_SUCCESS = "UPDATE_AVIS_SUCCESS";
export const UPDATE_AVIS_FAILURE = "UPDATE_AVIS_FAILURE";

// get statistics
export const FETCH_ALL_BEGIN = "FETCH_ALL_BEGIN";
export const FETCH_ALL_SUCCESS = "FETCH_ALL_SUCCESS";
export const FETCH_ALL_FAILURE = "FETCH_ALL_FAILURE";

  //Medecins
export const FETCH_MED_STAT_BEGIN = "FETCH_MED_STAT_BEGIN";
export const FETCH_MED_STAT_SUCCESS = "FETCH_MED_STAT_SUCCESS";
export const FETCH_MED_STAT_FAILURE = "FETCH_MED_STAT_FAILURE";

// users
export const ADD_USER_BEGIN = "ADD_USER_BEGIN";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";
export const FETCH_USERS_BEGIN = "FETCH_USERS_BEGIN";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS"; 
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE"; 

//exams
export const FETCH_EXAMS_BEGIN = "FETCH_EXAMS_BEGIN";
export const FETCH_EXAMS_SUCCESS = "FETCH_EXAMS_SUCCESS";
export const FETCH_EXAMS_FAILURE = "FETCH_EXAMS_FAILURE";
